name: 'sec_financial_intelligence'
version: '1.0.0'

profile: 'sec_financial_intelligence'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sec_financial_intelligence:
    staging:
      +materialized: view
    marts:
      +materialized: table
